arta_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('exhibition.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'documents_root':settings.MEDIA_ROOT}),
    # 디버깅 모드 해제할때 필요
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exhibition/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.SinglePage.landing_page),
    path('', views.ExhibitionList.as_view()),
    path('about/', views.SinglePage.about_page),
    path('credit/', views.SinglePage.credit_page),
    path('login/', views.SinglePage.login_page),

    path('preference/', views.LikePieceList.as_view()),
    path('preference/piece/', views.LikePieceList.as_view()),
    path('preference/exhibition/', views.LikeExhibitionList.as_view()),
    path('search/', views.SearchPage.search_page),
    path('search/result/piece/<str:q>/', views.PieceSearch.as_view()),
    path('search/result/exhibition/<str:q>/', views.ExhibitionSearch.as_view()),

    path('exhibition/', views.ExhibitionList.as_view()),
    path('exhibition/', views.ExhibitionList.as_view()),
    path('exhibition/<int:pk>/', views.PieceList.as_view()),
    path('exhibition/category/<str:slug>/', views.CategoryManage.category_page),
    path('exhibition/<int:pk>/new_guestbook/', views.GuestbookManage.new_guestbook),
    path('exhibition/delete_guestbook/<int:pk>/', views.GuestbookManage.delete_guestbook),
    path('exhibition/<int:pk>/new_like/', views.LikeManage.exhibition_like),
    path('exhibition/<int:ak>/dislike/<int:pk>/', views.LikeManage.exhibition_dislike),
    path('exhibition/<int:pk>/share/', views.ShareManage.exhibition_share),

    path('exhibition/piece/<int:pk>/', views.PieceDetail.as_view()),
    path('exhibition/piece/<int:pk>/new_comment/', views.CommentManage.new_comment),
    path('exhibition/piece/delete_comment/<int:pk>/', views.CommentManage.delete_comment),
    path('exhibition/piece/<int:pk>/new_like/', views.LikeManage.piece_like),
    path('exhibition/piece/<int:ak>/dislike/<int:pk>/', views.LikeManage.piece_dislike),
    path('exhibition/piece/<int:pk>/share/', views.ShareManage.piece_share),

]

exhibition/models.py
from django.db import models
from django.contrib.auth.models import User
import os


class Category(models.Model):
    bigName = models.CharField(max_length=50, unique=False, null=False)
    smallName = models.CharField(max_length=50, unique=True, null=False)
    slug = models.SlugField(max_length=50, unique=True, allow_unicode=True, null=False)
    image = models.ImageField(upload_to='category_images/', null=True, blank=True)

    def get_absolute_url(self):
        return f'/exhibition/category/{self.slug}/'

    def __str__(self):
        return self.smallName

    class Meta:
        verbose_name_plural = 'categories'


class Material(models.Model):
    name = models.CharField(max_length=50, null=False)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, null=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/piece/material/{self.slug}/'


class Exhibition(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    explain = models.TextField(null=False, blank=False)
    poster = models.ImageField(upload_to='exhibition/%Y/%m/%d/', blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    remove_at = models.DateTimeField(null=True, blank=True)
    start_at = models.DateTimeField(null=True, blank=True)
    end_at = models.DateTimeField(null=True, blank=True)
    click_count = models.IntegerField(default=0)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.name}'

    def get_absolute_url(self):
        return f'/exhibition/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.poster.name)


class Piece(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    explain = models.TextField(null=False, blank=False)
    author_say = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='piece/%Y/%m/%d/', null=False, blank=False)
    size = models.CharField(max_length=100, null=False, blank=False)
    author = models.CharField(max_length=50, null=False, blank=False)
    create_at = models.DateTimeField(auto_now_add=True, null=False)
    make_date = models.DateTimeField(auto_now=True, null=False)
    remove_at = models.DateTimeField(null=True, blank=True)
    order = models.IntegerField(null=True, blank=True)
    click_count = models.IntegerField(default=0)
    major = models.CharField(max_length=10, null=True, blank=True)
    number = models.IntegerField(null=True, blank=True)

    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, blank=True)
    material = models.ForeignKey(Material, null=True, on_delete=models.SET_NULL, blank=True)
    exhibition = models.ForeignKey(Exhibition, null=True, on_delete=models.SET_NULL, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/exhibition/piece/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.image.name)


class GuestBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    exhibition = models.ForeignKey(Exhibition, on_delete=models.SET_NULL, null=True, blank=True)
    content = models.TextField(null=False, blank=False)
    create_at = models.DateTimeField(auto_now_add=True, null=False)
    remove_at = models.DateTimeField(null=True, blank=True)

    def get_absolute_url(self):
        return f'/exhibition/{self.exhibition.pk}/'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    piece = models.ForeignKey(Piece, on_delete=models.SET_NULL, null=True, blank=True)
    content = models.TextField(null=False, blank=False)
    create_at = models.DateTimeField(auto_now_add=True, null=False)
    remove_at = models.DateTimeField(null=True, blank=True)

    def get_absolute_url(self):
        return f'/exhibition/piece/{self.piece.pk}/'


class InitialLike(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


class ExhibitionLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    exhibition = models.ForeignKey(Exhibition, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return f'/exhibition/{self.exhibition.pk}/'


class PieceLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    piece = models.ForeignKey(Piece, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return f'/exhibition/piece/{self.piece.pk}/'


class ExhibitionClick(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    exhibition = models.ForeignKey(Exhibition, on_delete=models.SET_NULL, null=True, blank=True)


class PieceClick(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    piece = models.ForeignKey(Piece, on_delete=models.SET_NULL, null=True, blank=True)


class ExhibitionShare(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    exhibition = models.ForeignKey(Exhibition, on_delete=models.SET_NULL, null=True, blank=True)


class PieceShare(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    piece = models.ForeignKey(Piece, on_delete=models.SET_NULL, null=True, blank=True)

exhibition/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

exhibition/templates/exhibition/ARTA_User_fine_exhibition_show.html
{% extends 'exhibition/ARTA_header.html' %}
{% load static %}
{% block header_title %}<title>{{ exhibition.name }}</title>{% endblock %}

{% block script_blcok %}
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://developers.kakao.com/sdk/js/kakao.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(window).scroll(function () {
                $('.piece_action').each(function (i) {
                    var bottom_of_object = $(this).offset().top + $(this).outerHeight();
                    var top_of_object = $(this).offset().top;
                    var middle_of_window = $(window).scrollTop() + $(window).height() / 2;
                    var windowWidth = $(window).width();

                    if (windowWidth < 992 && middle_of_window > top_of_object && middle_of_window < bottom_of_object) {
                        //$(this).animate({'opacity':'1','margin-left':'0px'},500);
                        if ($(this).css("opacity") == 0) {
                            $(this).fadeTo(500, 1);
                        }
                    } else { //object goes out of view (scrolling up)
                        if ($(this).css("opacity") == 1) {
                            $(this).fadeTo(500, 0);
                        }
                    }
                });
            });
        });

        //카카오 공유
        $(document).ready(function shareKakao() {
            Kakao.init('61d34319ce6231efe326b8125598493a');

            Kakao.Link.createDefaultButton({
                container: '#btnKakao',
                objectType: 'feed',
                content: {
                    title: "{{ exhibition.name }}",
                    description: "{{ piece.explain | truncatewords:12 }}",
                    imageUrl: "http://fine-village.co.kr/",
                    link: {
                        mobileWebUrl: window.location.href,  //카카오 앱
                        webUrl: window.location.href  //카카오 PC
                    }
                }
            });
        })
    </script>

    <script>
        // 모달 버튼에 이벤트를 건다.
        $('#open').on('click', function () {
            $('#modal').modal('show');
        });
        // 모달 안의 취소 버튼에 이벤트를 건다.
        $('#close').on('click', function () {
            $('#modal').modal('hide');
        });
    </script>

{% endblock %}
{% block style_blcok %}
    <link rel="stylesheet" href="{% static 'exhibition/css/exhibition_show_style.css' %}"/>
    <link rel="stylesheet" href="{% static 'exhibition/css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'exhibition/css/pagination.css' %}"/>
{% endblock %}
{% block main_blcok %}
    {% if messages %}
        {% for message in messages %}
            <script>
                alert("{{ message }}");
            </script>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="aside_container col-md-1 col-md-push-11">
            <h2 class="h_name"><a href="{{ exhibition.get_absolute_url }}">전시회 보기</a></h2>
            <div class="icon_row">
                <!--share icon-->
                <a class="share" id="btnKakao" href="javascript:shareKakao();">
                    <i class="fa fa-share-alt" style="font-size:13px" aria-hidden="true"></i>
                    <p class="icon_font"> 공유 </p>
                </a>
                <!--like icon-->
                {% if user.is_authenticated %}
                    {% if like_list %}
                        {% for like in like_list %}
                            <a class="bookmark" href="{{ exhibition.get_absolute_url }}dislike/{{ like.pk }}/">
                                <i class="fa fa-heart" aria-hidden="true"></i>
                                <p class="icon_font">좋아요 취소</p>
                            </a>
                        {% endfor %}
                    {% else %}
                        <a class="bookmark" href="{{ exhibition.get_absolute_url }}new_like/">
                            <i class="far fa-heart red" aria-hidden="true"></i>
                            <p class="icon_font"> 좋아요 </p>
                        </a>
                    {% endif %}
                {% endif %}
                <!--guestbook icon-->
                <button type="button" class="guest_book" id="open" data-toggle="modal" data-target="#modal">
                    <i class="fa fa-comment-alt" style="font-size:13px" aria-hidden="true"></i>
                    <p class="icon_font"> 방명록 </p>
                </button>
                <div class="modal fade" id="modal" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-Box" id="modal_content" role="document">
                            <p class="modal-name">전시회 방명록</p>
                            <button type="button" class="modal-close" id="close" data-dismiss="modal"><i
                                    class="fas fa-times"></i></button>

                            <!--guestbook list-->
                            <div class="comments">
                                <!--guestbook insert form-->
                                {% if user.is_authenticated %}
                                    <form id="comment-form" method="post"
                                          action="{{ exhibition.get_absolute_url }}new_guestbook/">
                                        {% csrf_token %}
                                        <div class="input-comment">
                                            <label for="new_comment"></label>
                                            <textarea class="form-control" id="new_comment" name="content" rows="3"
                                                      placeholder="방명록을 입력해주세요"></textarea>
                                            <button class="submit_btn" type="submit" onclick="submitComment()">OK!
                                            </button>
                                        </div>
                                    </form>
                                {% else %}
                                    <div class="input-comment">
                                        <p>로그인을 하셔야 방명록을 남길 수 있습니다.</p>
                                    </div>
                                {% endif %}


                                <!--guest book loop-->
                                {% if exhibition.guestbook_set.exists %}
                                    {% for guestbook in exhibition.guestbook_set.iterator %}
                                        <div class="comment-row">
                                            <div class="store-comment">
                                                <div class="comment-id">
                                                    <strong>{{ guestbook.user.username }}</strong>
                                                </div>
                                                <div class="comment-date">{{ guestbook.create_at }}</div>
                                                {% if guestbook.user == user and user.is_authenticated %}
                                                    <a href="/exhibition/delete_guestbook/{{ guestbook.pk }}">
                                                        <button class="cancel-button"><i class="fas fa-times"></i>
                                                        </button>
                                                    </a>
                                                {% endif %}
                                            </div>
                                            <div class="comment-content">{{ guestbook.content }}</div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    <p>아직 작성된 방명록이 없습니다! 당신이 첫번째 방명록을 달아주세여</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content_container col-md-11 col-md-pull-1">
            <!--exhibition-->
            <div class="article_container">
                <div class="exhibition_poster">
                    <div class="exhibition_info">
                        <br/>
                        <p class="exhibition_name"><strong>{{ exhibition.name }}</strong></p><br/>
                        <p class="exhibitor"><i class="fas fa-eye"></i> {{ exhibition.click_count }}</p><br/>
                        <p class="exhibit_day">{{ total }}개의 작품이 전시중이에요!</p><br/>
                    </div>
                </div>
                <div class="exhibition_main">
                    <!--piece list-->
                    <div class="piece_container">
                        <!--piece loop-->
                        {% if piece_list %}
                            {% for piece in piece_list %}
                                <!--piece-->
                                <div class="piece_img_block">
                                    <a href="{{ piece.get_absolute_url }}" class="img_block">
                                        <img class="piece_img" src="{{ piece.image.url }}"
                                             alt="그림이 서버에서 사라짐...ㅠㅠ"/>
                                        <div class="piece_action">
                                            <p>{{ piece.author }}</p>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if piece_list %}
            {% else %}
                <div style="margin-top: 10%;margin-bottom: 10%">
                    <p>아직 등록된 그림이 없습니다. 조금만 기다려~</p>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="footer_row col-xs-12"> <!--아래 페이징 공간-->
            <footer>
                {% if is_paginated %}
                    <p>- {{ page_obj.number }} -</p>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_next %}
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link"
                                                         href="?page={{ page_obj.previous_page_number }}">
                                    <i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake" href="#">
                                    <i class="" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake" href="#">
                                    <i class="" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                            {% else %}
                                <li class="page-item"><a class="page-fake disabled" href="">
                                    <i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake" href="#">
                                    <i class="" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake" href="#">
                                    <i class="" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                            {% endif %}
                        {% else %}
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link"
                                                         href="?page={{ page_obj.previous_page_number }}">
                                    <i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake" href="#">
                                    <i class="" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake" href="#">
                                    <i class="" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake disabled" href="">
                                    <i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                            {% else %}
                                <li class="page-item"><a class="page-fake disabled" href="">
                                    <i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake" href="#">
                                    <i class="" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake" href="#">
                                    <i class="" aria-hidden="true"></i></a></li>
                                <li class="page-item"><a class="page-fake disabled" href="">
                                    <i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                            {% endif %}
                        {% endif %}
                    </ul>
                {% else %}
                    <div style="height: 50px;"></div>
                {% endif %}
            </footer>
        </div>
    </div>
{% endblock %}

exhibition/templates/exhibition/ARTA_User_piece_show.html
{% extends 'exhibition/ARTA_header.html' %}
{% load static %}
{% block header_title %}<title>{{ piece.name }}</title>{% endblock %}

{% block script_blcok %}
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://developers.kakao.com/sdk/js/kakao.min.js"></script>
    <script>
        //카카오 공유
        $(document).ready(
            function shareKakao() {
                {#Kakao.init('61d34319ce6231efe326b8125598493a');#}
                Kakao.init('bb7f55b9f78127bb6d4d416fff4dacb4');
                Kakao.Link.createDefaultButton({
                    container: '#btnKakao',
                    objectType: 'feed',
                    content: {
                        title: "{{ piece.name }} - {{ piece.author }}",
                        description: "{{ piece.explain | truncatewords:12 }}",
                        imageUrl: "{{ piece.image.url }}",
                        link: {
                            mobileWebUrl: window.location.href,  //카카오 앱
                            webUrl: window.location.href  //카카오 PC
                        }
                    }
                });
            })
    </script>
{% endblock %}
{% block style_blcok %}
    <link rel="stylesheet" href="{% static 'exhibition/css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'exhibition/css/user_piece_show.css' %}"/>
    <link rel="stylesheet" href="{% static 'exhibition/css/pagination.css' %}"/>

    <style>
        .article_container {
            border-bottom: 1px solid #5CA4A2;
        }

        .exhibitor, .piece_name {
            font-weight: bold;
        }

        @media screen and (min-width: 768px) and (max-width: 991px) {
            .aside_container {
                display: none;
            }
        }

        @media screen and (min-width: 992px) {
            .aside_nav {
                display: none;
            }
        }
    </style>
{% endblock %}

{% block main_blcok %}
    {% if messages %}
        {% for message in messages %}
            <script>
                alert("{{ message }}");
            </script>
        {% endfor %}
    {% endif %}
    <div class="row">
        <!--title-->
        <div class="aside_container col-md-1 col-md-push-11">
            <p class="aside_nav">작품 보기</p>
        </div>
        <!--piece-->
        <div class="content_container col-md-11 col-md-pull-1">
            <div class="article_container">
                <div class="row row_content">
                    <div class="form-group">
                        <p class="piece_name col-xs-6">{{ piece.name }}</p>
                        <p class="exhibitor col-xs-6">{{ piece.author }}&nbsp;
                            {% if piece.remove_at %}
                            ({{ piece.remove_at.year }}作)
                            {% endif %}
                        </p>
                    </div>
                </div>

                <!--작품 설명-->
                <div class="row row_content">
                    <div class="explain_piece">
                        <p class="explanation text-left">{{ piece.explain }}</p>
                    </div>
                </div>

                <div class="row row_content">
                    <div class="form-group">
                        <img class="piece" src="{{ piece.image.url }}" alt="서버에서 파일이 증발함...ㅠㅠ">
                    </div>
                </div>

                <!--작품 설명-->
                {% if piece.author_say %}
                    <p class="">작가 노트</p>
                    <div class="row row_content">
                        <p class="view">{{ piece.author_say }}</p>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="piece_size">
                        <p class="size">{{ piece.size }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="piece_size">
                        <p class="size">{{ piece.material.name }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="piece_size">
                        <p class="size">{{ piece.major }} ( {{ piece.number }} )</p>
                    </div>
                </div>

                <div class="row">
                    <div class="piece_size">
                        <p class="view"><i class="fas fa-eye"></i> {{ piece.click_count }}</p>
                    </div>
                </div>


                <div class="icon"> <!--공유 버튼, 좋아요 버튼-->
                    <!--share icon-->
                    <a class="share" id="btnKakao" href="javascript:shareKakao();">
                        <i class="fa fa-share-alt" aria-hidden="true"></i></a>
                    <!--like icon-->
                    {% if user.is_authenticated %}
                        {% if like_list %}
                            {% for like in like_list %}
                                <a class="bookmark" href="{{ piece.get_absolute_url }}dislike/{{ like.pk }}/">
                                    <i class="fa fa-heart" aria-hidden="true"></i>
                                </a>
                            {% endfor %}
                        {% else %}
                            <a class="bookmark" href="{{ piece.get_absolute_url }}new_like/">
                                <i class="far fa-heart" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                    {% endif %}
                </div>

                <!--댓글-->
                <div class="comments">
                    <!--comment form-->
                    {% if user.is_authenticated %}
                        <form id="comment-form" method="post" action="{{ piece.get_absolute_url }}new_comment/">
                            {% csrf_token %}
                            <div class="input-comment">
                                <!-- <div class="user_name">사용자 이름</div> -->
                                <label for="new-comment"></label>
                                <textarea id="new-comment" class="form-control" name="content" rows="2"
                                          placeholder="댓글을 입력해주세요"></textarea>
                                <button class="submit_btn" type="submit" onclick="submitComment()">OK!</button>
                            </div>
                        </form>
                    {% else %}
                        <div class="input-comment">
                            <p>로그인을 하셔야 댓글을 달 수 있습니다.</p>
                        </div>
                    {% endif %}

                    <!--comment loop-->
                    {% if piece.comment_set.exists %}
                        {% for comment in piece.comment_set.iterator %}
                            <div class="comment-row">
                                <div class="comment_list">
                                    <div class="user_name">{{ comment.user.username }}</div>
                                    <div class="comment-date">{{ comment.create_at }}</div>
                                    {% if comment.user == user and user.is_authenticated %}
                                        <a href="/exhibition/piece/delete_comment/{{ comment.pk }}/">
                                            <div class="comment-delete">삭제</div>
                                        </a>
                                    {% endif %}
                                    <div class="comment-content">{{ comment.content }}</div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>아직 작성된 댓글이 없습니다! 당신이 첫번째 댓글을 달아주세요!</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="footer_row col-xs-12"> <!--아래 페이징 공간-->
            <footer>
                <div style="height: 50pt;"></div>
            </footer>
        </div>
    </div>
{% endblock %}

exhibition/templates/exhibition/ARTA_footer.html
<!--footer-->
<footer style="padding: 3rem;background-color: #5eaaa8;">
    <div class="container">
        <p style="color: #fff; text-align: center;margin: 0;">
            Copyright &copy; 화인부락
        </p>
        <p style="color: #fff; text-align: center;margin: 0;">
            문의 wnsdud9641@naver.com
        </p>
    </div>
</footer>